# Setup

In [1]:
# Libraries
import os
import pandas as pd
import numpy as np
import pprint

# Show all output from the code box, not just last line
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# Show all cols and rows in view
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)

# ignore future warnings
import warnings
warnings.filterwarnings('ignore')
warnings.simplefilter(action="ignore", category=FutureWarning)

# Data folder path
fpath = "..."

# Load data

In [2]:
# Data.
import pyreadstat
df0, meta = pyreadstat.read_sav(os.path.join(fpath,"Raw","public-use/prgushp1_puf (2012-2014).sav"))
df0_labelled, meta2 = pyreadstat.read_sav(os.path.join(fpath,"Raw","public-use/prgushp1_puf (2012-2014).sav"), 
                                          apply_value_formats=True)

In [3]:
df0.head()

,CNTRYID,CNTRY,CNTRYID_E,CNTRY_E,SEQID,GENDER_R,DISP_CIBQ,A_N01_T,B_Q01A,B_Q01A_T,B_Q01B,B_Q01C1_C,B_D01D_C,B_Q02A,B_Q02A_T1,B_Q02A_T2,B_Q03A,B_Q03C1_C,B_D03D_C,B_Q04A,B_Q04B_C,B_Q05C,B_Q05C_T,B_Q10A,B_Q10B,B_Q10C,B_Q11,B_Q12A,B_Q12A_T,B_Q12C,B_Q12D_C,B_Q12E,B_Q12F_C,B_Q12G,B_Q12H_C,B_D12H,B_Q13,B_Q14A,B_Q14B,B_Q15A,B_Q15B,B_Q15C,B_Q16,B_Q17,B_Q18A,B_Q19A,B_Q20A,B_Q20B,B_Q26A,B_Q26A_T,B_Q26B,C_Q01A,C_Q01B,C_Q01C,C_Q02A,C_Q02B,C_Q03_01,C_Q03_02,C_Q03_03,C_Q03_04,C_Q03_05,C_Q03_06,C_Q03_07,C_Q03_08,C_Q03_09,C_Q03_10,C_Q04A,C_Q04B,C_Q04C,C_Q04D,C_Q04E,C_Q04F,C_Q04G,C_Q04H,C_Q04J,C_D04,C_D05,C_Q06,C_D06,C_Q07,C_Q07_T,C_Q08A,C_Q08B,C_Q08C1_C,C_D08C,C_Q09_C,C_D09,C_D09_T,C_Q10A_C,D_Q03,D_Q04,D_Q04_T,D_Q04_T1,D_Q05A1_C,D_Q05B1_C,D_Q06A,D_Q06B,D_Q06C,D_Q07A,D_Q07B_C,D_Q08A,D_Q08B,D_Q10,D_Q10_C,D_Q10_T,D_Q10_T1,D_Q11A,D_Q11B,D_Q11C,D_Q11D,D_Q12A,D_Q12B,D_Q12C,D_Q13A,D_Q13B,D_Q13C,D_Q14,D_Q16A,D_D16A,D_Q16C,D_Q17A,D_Q17C,D_Q18B,E_Q03,E_Q04,E_Q05A1_C,E_Q05B1_C,E_Q06,E_Q09,E_Q09_C,E_Q10,F_Q01B,F_Q02A,F_Q02B,F_Q02C,F_Q02D,F_Q02E,F_Q03A,F_Q03B,F_Q03C,F_Q04A,F_Q04B,F_Q05A,F_Q05B,F_Q06B,F_Q06C,F_Q07A,F_Q07B,G_Q01A,G_Q01A_T,G_Q01A_T1,G_Q01B,G_Q01B_T,G_Q01B_T1,G_Q01C,G_Q01C_T,G_Q01C_T1,G_Q01D,G_Q01E,G_Q01F,G_Q01F_T,G_Q01F_T1,G_Q01G,G_Q01G_T,G_Q01G_T1,G_Q01H,G_Q01H_T,G_Q01H_T1,G_Q02A,G_Q02B,G_Q02C,G_Q02D,G_Q03B,G_Q03C,G_Q03D,G_Q03F,G_Q03G,G_Q03H,G_Q04,G_Q04_T,G_Q05A,G_Q05C,G_Q05D,G_Q05E,G_Q05F,G_Q05G,G_Q05H,G_Q06,G_Q07,G_Q08,H_Q01A,H_Q01B,H_Q01B_T,H_Q01C,H_Q01C_T,H_Q01D,H_Q01E,H_Q01E_T,H_Q01F,H_Q01G,H_Q01H,H_Q02A,H_Q02B,H_Q02C,H_Q02D,H_Q03B,H_Q03C,H_Q03D,H_Q03F,H_Q03G,H_Q03H,H_Q04A,H_Q04B,H_Q05A,H_Q05C,H_Q05D,H_Q05E,H_Q05F,H_Q05G,H_Q05H,I_Q04B,I_Q04D,I_Q04H,I_Q04J,I_Q04L,I_Q04M,I_Q05F,I_Q06A,I_Q07A,I_Q07B,I_Q08,I_Q08_T,J_Q01_C,J_Q01_T1,J_Q02A,J_Q02C,J_Q03A,J_Q03B_C,J_Q03C_C,J_Q03D1_C,J_Q03D2_C,J_Q04A,J_Q04A_T,J_Q04C1_C,J_Q04C2_T1,J_N05A2,J_Q06A,J_Q06A_T,J_Q06B,J_Q06B_T,...,PVPSL1,PVPSL2,PVPSL3,PVPSL4,PVPSL5,PVPSL6,PVPSL7,PVPSL8,PVPSL9,PVPSL10,PRC_PV_SCR,PRC_SP_SCR,PRC_PC_SCR,VEMETHOD,VEMETHODN,VEFAYFAC,VENREPS,VARSTRAT,VARUNIT,SPFWT0,SPFWT1,SPFWT2,SPFWT3,SPFWT4,SPFWT5,SPFWT6,SPFWT7,SPFWT8,SPFWT9,SPFWT10,SPFWT11,SPFWT12,SPFWT13,SPFWT14,SPFWT15,SPFWT16,SPFWT17,SPFWT18,SPFWT19,SPFWT20,SPFWT21,SPFWT22,SPFWT23,SPFWT24,SPFWT25,SPFWT26,SPFWT27,SPFWT28,SPFWT29,SPFWT30,SPFWT31,SPFWT32,SPFWT33,SPFWT34,SPFWT35,SPFWT36,SPFWT37,SPFWT38,SPFWT39,SPFWT40,SPFWT41,SPFWT42,SPFWT43,SPFWT44,SPFWT45,SPFWT46,SPFWT47,SPFWT48,SPFWT49,SPFWT50,SPFWT51,SPFWT52,SPFWT53,SPFWT54,SPFWT55,SPFWT56,SPFWT57,SPFWT58,SPFWT59,SPFWT60,SPFWT61,SPFWT62,SPFWT63,SPFWT64,SPFWT65,SPFWT66,SPFWT67,SPFWT68,SPFWT69,SPFWT70,SPFWT71,SPFWT72,SPFWT73,SPFWT74,SPFWT75,SPFWT76,SPFWT77,SPFWT78,SPFWT79,SPFWT80,INPIAAC,B_Q05CUSX1,B_Q05CUSX2,B_Q14BUSX1,B_Q14BUSX2,B_Q27AUSX,B_Q27BUSX,B_Q27CUSX,B_Q27DUSX,B_Q29AUSX,D_Q03US,E_Q03US,I_Q06DUSX1A,I_Q06DUSX1B,I_Q06DUSX1C,I_Q06DUSX1D,I_Q06DUSX1E,I_Q06DUSX1F,I_Q06DUSX1G,I_Q08USX1,I_Q08USX2,I_Q08USX3,I_Q10BUSX2A,I_Q10BUSX2B,I_Q10BUSX2C,I_Q10BUSX2D,I_Q10BUSX2E,I_Q10BUSX2F,I_Q10BUSX2G,I_Q10BUSX2H,I_Q10BUSX3A,I_Q10BUSX3B,I_Q10BUSX3C,I_Q10BUSX3D,I_Q10BUSX3E,I_Q10BUSX3F,I_Q10BUSX3G,I_Q10BUSX3H,J_Q04DUSX1A,J_Q05A2USX2,J_Q05CUSX2,J_Q05CUSX3A,J_Q05CUSX3B,J_Q05CUSX3D,J_Q05CUSX3E,J_Q05CUSX4,J_Q05CUSX6,J_Q06BUS,J_Q07BUS,REGION_US,B_Q01A_C,B_Q01AUS_C,B_Q02BUS_C,B_Q02CUS_C,B_Q03BUS_C,B_Q12BUS_C,C_S03US_C,C_Q08C2US_C,D_Q05A2US_C,D_Q05B2US_C,D_Q09US_C,D_Q12A_C,D_Q12AUS_C,D_Q16BUS_C,D_Q17BUS_C,E_Q05A2US_C,E_Q05B2US_C,E_Q08US_C,J_Q03CUS_C,J_Q03D1US_C,J_Q03D2US_C,J_Q04C2US_C,BIRTHRGNUS_C,CNT_BRTHUS_C,FIRLGRGNUS_C,HOMLGRGNUS_C,LANGUAGE,LNG_HOMEUS_C,LNG_L1US_C,LNG_L2US_C,SECLGRGNUS_C,RACETHN_4CAT,RACETHN_5CAT,LEAVEDUUS_C,ISCO08_CUS_C,ISCO08_LUS_C,ISCO08_US_C,ISIC4_CUS_C,ISIC4_LUS_C,USCIP_C_C,USCIP_H_C,USCIP_L_C,SAMPFLAG,I_Q10BUSX1,AGEG5LFSEXT,AGEG10LFSEXT,AGE1634,AGE6674,INTLFLAG,EMP_6CAT,UNEMPFLAG,URBAN_4CAT,B_Q01A_ISCED11,D_Q12A_ISCED11,J_Q06B_ISCED11,J_Q07B_ISCED11,LEARNATWORK,LEARNATWORK_WLE_CA,READYTOLEARN,READYTOLEARN_WLE_CA,ICTHOME,ICTHOME_WLE_CA,ICTWORK,ICTWORK_WLE_CA,INFLUENCE,INFLUENCE_WLE_CA,NUMHOME,NUMHOME_WLE_CA,NUMWORK,NUMWORK_WLE_CA,PLANNING,PLANNING_WLE_CA,READHOME,READHOME_WLE_CA,READWORK,READWORK_WLE_CA,TASKDISC,TASKDISC_WLE_CA,WRITHOME,WRITHOME_WLE_CA,WRITWORK,WRITWORK_WLE_CA,EARNHRDCL,EARNHRBONUSDCL,EARNMTHALLDCL,EARNFLAG,D_Q18A_T,PAIDWORK5,EMPSTAT,EARNHRUS_C,EARNHRPPPUS_C,EARNHRBONUSUS_C,EARNHRBONUSPPPUS_C,EARNMTHUS_C,EARNMTHPPPUS_C,EARNMTHBONUSUS_C,EARNMTHBONUSPPPUS_C,EARNMTHALLUS_C,EARNMTHALLPPPUS_C,EARNMTHSELFPPPUS_C
0,84091.0,USA,840.0,USA,1.0,2.0,1.0,2.0,7.0,2.0,NaN,2.0,NaN,2.0,1.0,1.0,1.0,5.0,1.0,NaN,NaN,2.0,2.0,1.0,4.0,1.0,3.0,2.0,2.0,2.0,NaN,2.0,NaN,2.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,9.0,5.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,4.0,NaN,2.0,3.0,1.0,NaN,NaN,1.0,1.0,60.0,60.0,60.0,3.0,5.0,4.0,5.0,5.0,7.0,2.0,1.0,5.0,2.0,5.0,5.0,5.0,173.00,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,5.0,3.0,1.0,5.0,1.0,1.0,1.0,5.0,5.0,1.0,3.0,2.0,5.0,5.0,1.0,2.0,5.0,1.0,1.0,5.0,1.0,1.0,1.0,4.0,3.0,1.0,1.0,5.0,1.0,1.0,5.0,1.0,1.0,5.0,1.0,1.0,1.0,1.0,5.0,5.0,1.0,1.0,1.0,5.0,1.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,1.0,5.0,1.0,1.0,2.0,3.0,1.0,5.0,1.0,2.0,1.0,1.0,2.0,4.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,5.0,2.0,3.0,4.0,4.0,1.0,1.0,1.0,1.0,2.0,2.0,4.0,4.0,2.0,NaN,1.0,3.0,NaN,2.0,4.0,1.0,1.0,NaN,NaN,2.0,1.0,1.0,3.0,3.0,...,293.84784,264.13851,245.65246,273.33731,273.15058,278.67009,265.98190,267.82308,267.40297,252.45366,NaN,NaN,NaN,JK2,2.0,0.0,45.0,10.0,2.0,9335.815935,9343.637643,9304.097906,9260.400603,9193.732034,10544.862048,9078.357588,9406.028303,8676.943212,9164.733928,17559.156590,9179.683570,9864.203891,9274.957579,10171.850245,9407.942868,9268.463980,9349.465040,9527.079190,9289.451857,9262.675753,9439.992359,9014.461787,9259.501219,8875.751349,9460.590112,9233.178577,9324.647521,9301.745119,9720.587839,9033.945978,9651.394649,9212.488606,9264.309373,9435.278907,9391.073803,9495.381696,9227.475381,9995.490512,9389.137536,9230.886188,9642.731012,9311.316247,9520.343044,9298.782762,9398.031573,9335.815935,9335.815935,9335.815935,9335.815935,9335.815935,9335.815935,9335.815935,9335.815935,9335.815935,9335.815935,9335.815935,9335.815935,9335.815935,9335.815935,9335.815935,9335.815935,9335.815935,9335.815935,9335.815935,9335.815935,9335.815935,9335.815935,9335.815935,9335.815935,9335.815935,9335.815935,9335.815935,9335.815935,9335.815935,9335.815935,9335.815935,9335.815935,9335.815935,9335.815935,9335.815935,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,NaN,3.0,3.0,3.0,3.0,1.0,3.0,1.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,3.0,4.0,2.0,2.0,2.0,NaN,1.0,NaN,2.0,NaN,NaN,2.0,2.0,NaN,NaN,1.0,1.0,1.0,1.0,NaN,NaN,3.0,2.0,3.0,2.0,2.0,NaN,NaN,2.0,NaN,NaN,NaN,4.0,NaN,1.0,2.0,2.0,1800.0,NaN,NaN,NaN,NaN,NaN,2.0,4.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,3.0,3.0,5.0,432,9996,9999,463,9996,99999,99999,51.08,1.0,1.0,4.0,2.0,1.0,0.0,1.0,1.0,0.0,1.0,4.0,4.0,3.0,2.0,1.986379,3.0,1.686323,2.0,NaN,NaN,NaN,NaN,1.528612,2.0,1.124303,1.0,1.036985,1.0,0.819297,1.0,2.173975,3.0,1.958829,3.0,3.088914,5.0,1.070335,2.0,2.326391,4.0,1.0,1.0,4.0,1.0,2.0,1.0,2.0,6.936416,6.936416,6.936416,6.936416,1800.000000,1800.000000,1800.000000,1800.000000,1800.000000,1800.000000,NaN
1,84091.0,USA,840.0,USA,2.0,2.0,1.0,2.0,7.0,2.0,NaN,2.0,NaN,2.0,2.0,2.0,2.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,NaN,2.0,NaN,2.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,4.0,9.0,5.0,2.0,NaN,NaN,NaN,NaN,4.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5.0,1.0,5.0,1.0,3.0,4.0,1.0,2.0,5.0,1.0,4.0,1.0,1.0,1.0,2.0,2.0,2.0,3.0,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.0,4.0,4.0,4.0,3.0,3.0,1.0,1.0,2.0,4.0,4.0,2.0,2.0,1.0,6.0,1.0,4.0,NaN,4.0,4.0,1.0,1.0,NaN,NaN,2.0,1.0,1.0,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.0,20.0,37.0,JK2,2.0,0.0,45.0,31.0,1.0,24555.862320,24559.314364,24667.817431,24592.705481,20677.895347,24063.652999,22621.339894,24344.877688,24315.688081,24501.997529,24052.796735,23867.029178,26556.863302,24144.457197,24734.615465,24438.927717,24722.735194,24802.857222,24284.154812,24549.924310,26008.245801,23772.780927,24306.367237,28448.238917,24551.978004,24815.233683,23827.005046,23966.513251,24607.414274,24405.897327,24301.584711,47272.576778,24537.622555,24747.961829,24597.707663,23748.839227,24614.864285,24590.624809,26021.269892,24688.045002,24496.573876,24570.451176,24856.575145,24405.861503,24531.716485,24463.908213,24555.862320,24555.862320,24555.862320,24555.862320,24555.862320,24555.862320,24555.862320,24555.862320,24555.862320,24555.862320,24555.862320,24555.862320,24555.862320,24555.862320,24555.862320,24555.862320,24555.862320,24555.862320,24555.862320,24555.862320,24555.862320,24555.862320,24555.862320,24555.862320,24555.862320,24555.862320,24555.862320,24555.862320,24555.862320,24555.862320,24555.862320,24555.862320,24555.862320,24555.862320,24555.862320,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,1.0,3.0,4.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,4.0,1.0,1.0,3.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,NaN,1.0,1.0,2.0,NaN,NaN,1.0,1.0,1.0,1.0,NaN,NaN,2.0,NaN,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,NaN,1.0,1.0,1.0,NaN,1.0,NaN,1.0,NaN,NaN,2.0,2.0,2.0,9996,9996,9999,9996,9996,99999,99999,99999,1.0,1.0,12.0,6.0,0.0,1.0,0.0,6.0,0.0,2.0,4.0,NaN,2.0,NaN,NaN,NaN,1.532373,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.193614,3.0,NaN,NaN,NaN,NaN,2.608917,4.0,NaN,NaN,NaN,NaN,1.033728,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,84091.0,USA,840.0,USA,3.0,1.0,1.0,1.0,12.0,3.0,4.0,3.0,NaN,2.0,1.0,2.0,2.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,1.0,2.0,1.0,3.0,2.0,NaN,2.0,3.0,1.0,NaN,1.0,1.0,4.0,1.0,2.0,NaN,5.0,NaN,5.0,2.0,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,29.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0,4.0,NaN,4.0,3.0,1.0,NaN,NaN,1.0,5.0,55.0,55.0,55.0,3.0,5.0,4.0,5.0,2.0,12.0,1.0,6.0,4.0,2.0,3.0,1.0,5.0,173.00,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,5.0,5.0,2.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,2.0,2.0,5.0,1.0,2.0,5.0,1.0,1.0,5.0,1.0,1.0,5.0,1.0,1.0,3.0,2.0,4.0,1.0,1.0,5.0,1.0,1.0,2.0,3.0,3.0,5.0,1.0,5.0,5.0,5.0,5.0,5.0,3.0,5.0,5.0,1.0,1.0,5.0,4.0,5.0,5.0,5.0,1.0,3.0,1.0,1.0,1.0,4.0,5.0,1.0,5.0,1.0,3.0,3.0,2.0,3.0,5.0,3.0,4.0,1.0,2.0,3.0,4.0,3.0,5.0,3.0,4.0,3.0,NaN,1.0,5.0,4.0,4.0,3.0,3.0,1.0,2.0,3.0,5.0,4.0,5.0,4.0,5.0,1.0,2.0,2.0,2.0,1.0,1.0,4.0,4.0,1.0,2.0,1.0,2.0,NaN,4.0,4.0,1.0,1.0,NaN,NaN,2.0,1.0,1.0,2.0,2.0,...,301.55177,288.45475,289.30603,271.61450,283.15242,303.35927,271.70131,290.11247,320.23915,284.82614,NaN,NaN,NaN,JK2,2.0,0.0,45.0,29.0,1.0,60563.542690,59926.989701,59112.998559,60131.721085,60838.402612,60103.632561,60463.590695,59997.757477,68025.922443,63170.797783,61335.403053,64520.934507,61303.811004,60691.395006,61595.025206,61596.943148,60297.895100,59355.058382,60471.647395,61799.419562,61221.758172,60727.526357,60654.037463,60174.103399,60455.997668,60229.125291,59135.849736,60123.838118,59251.656555,117803.542230,61408.751509,60785.254640,60553.797173,59192.812359,60167.000317,59456.386138,65080.951519,59334.007125,57288.087892,60138.678643,60669.424068,59842.549756,60907.229370,58888.803714,60441.422396,59749.614979,60563.542690,60563.542690,60563.542690,60563.542690,60563.542690,60563.542690,60563.542690,60563.542690,60563.542690,60563.542690,60563.542690,60563.542690,60563.542690,60563.542690,60563.542690,60563.542690,60563.542690,60563.542690,60563.542690,60563.542690,60563.542690,60563.542690,60563.542690,60563.542690,60563.542690,60563.542690,60563.542690,60563.542690,60563.542690,60563.542690,60563.542690,60563.542690,60563.542690,60563.542690,60563.542690,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,2.0,1.0,NaN,1.0,2.0,1.0,4.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,4.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,2.0,1.0,2.0,2.0,1.0,2.0,NaN,NaN,1.0,1.0,1.0,1.0,NaN,NaN,2.0,3.0,4.0,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,4.0,3.0,3.0,8500.0,8.0,NaN,NaN,NaN,NaN,4.0,5.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,2.0,2.0,3.0,112,9996,9999,451,9996,99999,52.03,99999,1.0,1.0,8.0,4.0,0.0,0.0,1.0,1.0,0.0,1.0,7.0,7.0,2.0,3.0,1.557160,2.0,2.916617,5.0,2.727385,4.0,3.564468,5.0,3.480417,5.0,3.393321,5.0,4.361635,5.0,3.734814,5.0,3.047967,5.0,2.780542,5.0,2.716861,5.0,2.857830,5.0,3.690521,5.0,9.0,9.0,10.0,1.0,5.0,1.0,2.0,35.733053,35.733053,39.229557,39.229557,8500.000000,8500.000000,9333.333333,9333.333333,9333.333333,9333.333333,NaN
3,84091.0,USA,840.0,USA,4.0,2.0,1.0,2.0,12.0,3.0,4.0,3.0,NaN,2.0,1.0,2.0,2.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,1.0,2.0,1.0,1.0,2.0,NaN,2.0,3.0,1.0,NaN,1.0,1.0,4.0,1.0,2.0,NaN,5.0,NaN,5.0,2.0,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,6.0,1.0,1.0,1.0,3.0,1.0,1.0,1.0,2.0,NaN,2.0,2.0,2.0,NaN,NaN,2.0,NaN,40.0,40.0,40.0,2.0,1.0,4.0,3.0,3.0,12.0,1.0,6.0,2.0,3.0,4.0,3.0,6.0,2080.00,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5.0,4.0,2.0,1.0,5.0,5.0,4.0,5.0,3.0,3.0,5.0,4.0,2.0,1.0,1.0,2.0,3.0,2.0,2.0,5.0,1.0,1.0,3.0,2.0,2.0,3.0,2.0,1.0,4.0,3.0,4.0,1.0,1.0,4.0,1.0,1.0,5.0,1.0,2.0,2.0,5.0,3.0,5.0,2.0,1.0,1.0,1.0,1.0,5.0,5.0,3.0,5.0,5.0,1.0,2.0,2.0,1.0,2.0,2.0,5.0,1.0,5.0,1.0,2.0,4.0,1.0,2.0,4.0,3.0,5.0,1.0,1.0,2.0,2.0,1.0,3.0,1.0,1.0,1.0,NaN,1.0,5.0,5.0,4.0,3.0,3.0,1.0,2.0,3.0,5.0,4.0,5.0,5.0,5.0,2.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,2.0,1.0,1.0,3.0,3.0,...,318.86517,335.71306,328.44125,318.93160,330.29128,351.31326,322.81609,359.94806,321.08724,342.75098,NaN,NaN,NaN,JK2,2.0,0.0,45.0,26.0,1.0,32689.308788,32041.720267,33000.099677,31884.744549,31119.240627,32357.724429,31908.409661,32543.928256,30988.827877,32839.500515,31535.863118,30971.422980,33095.314155,31408.641396,32719.451493,31805.713922,32616.896378,31187.444228,33152.667122,32898.169579,33850.529801,32183.163119,32932.029163,32537.342433,32128.054790,32572.664541,61292.692314,33810.460818,32305.862841,33258.699436,33252.833330,32564.336495,33315.504198,32267.615316,32961.784717,33053.149278,32564.838881,32985.232345,32085.742136,31509.381988,32663.636784,33133.819306,32976.821683,32870.370523,32767.442271,32730.432111,32689.308788,32689.308788,32689.308788,32689.308788,32689.308788,32689.308788,32689.308788,32689.308788,32689.308788,32689.308788,32689.308788,32689.308788,32689.308788,32689.308788,32689.308788,32689.308788,32689.308788,32689.308788,32689.308788,32689.308788,32689.308788,32689.308788,32689.308788,32689.308788,32689.308788,32689.308788,32689.308788,32689.308788,32689.308788,32689.308788,32689.308788,32689.308788,32689.308788,32689.308788,32689.308788,1.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,2.0,3.0,NaN,2.0,2.0,1.0,3.0,3.0,4.0,1.0,2.0,2.0,2.0,3.0,4.0,1.0,2.0,2.0,4.0,1.0,2.0,2.0,NaN,1.0,NaN,1.0,NaN,NaN,1.0,2.0,NaN,NaN,1.0,1.0,1.0,1.0,NaN,NaN,3.0,3.0,3.0,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,1.0,3.0,3.0,57000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,NaN,1.0,NaN,1.0,NaN,NaN,2.0,2.0,3.0,333,9996,9999,823,9996,99999,52.14,99999,1.0,1.0,3.0,2.0,1.0,0.0,1.0,1.0,0.0,1.0,7.0,7.0,3.0,3.0,1.523923,2.0,3.264357,5.0,2.832901,5.0,3.308333,5.0,2.367685,4.0,1.138663,1.0,2.027366,3.0,3.010131,4.0,2.499774,4.0,2.234478,3.0,1.370868,2.0,2.438870,3.0,1.741687,3.0,8.0,8.0,8.0,1.0,4.0,1.0,2.0,27.403846,27.403846,27.403846,27.403846,4750.000000,4750.000000,4750.000000,4750.000000,4750.000000,4750.000000,NaN
4,84091.0,USA,840.0,USA,5.0,2.0,1.0,2.0,7.0,2.0,8.0,2.0,NaN,2.0,1.0,1.0,1.0,4.0,1.0,NaN,NaN,1.0,1.0,1.0,3.0,4.0,2.0,2.0,1.0,2.0,NaN,1.0,1.0,2.0,NaN,1.0,NaN,1.0,NaN,1.0,1.0,2.0,1.0,2.0,NaN,12.0,NaN,NaN,1.0,1.0,4.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,7.0,1.0,1.0,3.0,1.0,1.0,1.0,1.0,1.0,NaN,3.0,3.0,2.0,NaN,NaN,2.0,NaN,38.0,38.0,38.0,2.0,3.0,3.0,3.0,2.0,7.0,1.0,3.0,5.0,4.0,3.0,1.0,1.0,1.05,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,2.0,1.0,1.0,5.0,5.0,2.0,5.0,5.0,4.0,4.0,2.0,5.0,5.0,1.0,2.0,4.0,1.0,1.0,3.0,2.0,2.0,3.0,2.0,2.0,3.0,1.0,2.0,3.0,3.0,4.0,1.0,1.0,5.0,1.0,1.0,1.0,1.0,1.0,4.0,1.0,4.0,2.0,1.0,4.0,1.0,1.0,1.0,3.0,3.0,2.0,1.0,5.0,1.0,1.0,2.0,1.0,2.0,5.0,4.0,1.0,4.0,1.0,3.0,4.0,1.0,3.0,4.0,2.0,2.0,1.0,1.0,2.0,5.0,4.0,3.0,1.0,4.0,1.0,NaN,1.0,4.0,4.0,4.0,1.0,2.0,1.0,1.0,4.0,4.0,3.0,3.0,3.0,4.0,2.0,4.0,4.0,3.0,4.0,4.0,3.0,3.0,1.0,7.0,1.0,2.0,NaN,3.0,3.0,1.0,1.0,NaN,NaN,2.0,1.0,1.0,2.0,2.0,...,324.68964,302.02831,287.01258,317.24939,300.53521,310.77074,295.60636,294.55197,268.06415,279.62886,NaN,NaN,NaN,JK2,2.0,0.0,45.0,10.0,2.0,16601.114646,16110.878568,16596.879268,16570.151855,15745.670243,16226.380694,16561.373553,16415.716880,15844.966655,16695.658658,31380.389701,16124.325828,16717.850136,16590.841638,16373.323439,16423.328505,16565.190204,16283.771200,16352.031451,16475.237749,16776.414674,16628.435662,16778.829431,17197.797206,16271.963399,16611.214572,16966.403374,17585.935113,16860.928667,17492.562549,17305.101123,16632.909296,16118.327018,16622.086631,16683.463779,16472.465459,16324.386249,16525.039362,16125.076339,16498.259276,16518.563694,16680.349872,16729.950935,16723.645854,16601.211940,16539.006671,16601.114646,16601.114646,16601.114646,16601.114646,16601.114646,16601.114646,16601.114646,16601.114646,16601.114646,16601.114646,16601.114646,16601.114646,16601.114646,16601.114646,16601.114646,16601.114646,16601.114646,16601.114646,16601.114646,16601.114646,16601.114646,16601.114646,16601.114646,16601.114646,16601.114646,16601.114646,16601.114646,16601.114646,16601.114646,16601.114646,16601.114646,16601.114646,16601.114646,16601.114646,16601.114646,1.0,1.0,NaN,1.0,NaN,2.0,2.0,2.0,NaN,2.0,1.0,NaN,2.0,3.0,1.0,4.0,1.0,3.0,3.0,2.0,1.0,2.0,4.0,4.0,1.0,4.0,2.0,3.0,2.0,2.0,2.0,NaN,1.0,NaN,2.0,NaN,NaN,1.0,2.0,NaN,NaN,1.0,1.0,1.0,1.0,NaN,NaN,2.0,1.0,3.0,2.0,2.0,NaN,NaN,2.0,NaN,NaN,NaN,3.0,NaN,4.0,2.0,2.0,8.5,2.0,NaN,NaN,NaN,NaN,3.0,3.0,NaN,1.0,1.0,1.0,NaN,1.0,NaN,1.0,NaN,NaN,2.0,2.0,4.0,226,9996,9999,871,9996,99999,51.08,51.31,1.0,1.0,3.0,2.0,1.0,0.0,1.0,1.0,0.0,4.0,4.0,4.0,2.0,1.0,2.450471,4.0,1.687273,2.0,1.621030,2.0,1.153672,2.0,2.269413,4.0,2.803284,4.0,1.848566,3.0,1.958027,4.0,2.802664,5.0,2.154052,3.0,1.466427,2.0,1.070335,2.0,0.762984,1.0,2.0,2.0,3.0,1.0,2.0,1.0,2.0,8.500000,8.500000,8.651822,8.651822,1399.666667,1399.666667,1424.666667,1424.666667,1424.666667,1424.666667,NaN

In [4]:
# get value labels
for i in ['C_Q07','YEARLYINCPR','AGEG10LFS_T','RACETHN_4CAT','EDCAT6','GENDER_R','J_Q04A','REGION_US']:
    print(f"\033[1mValue labels for column '{i}':\033[0m")
    pprint.pprint(meta.variable_value_labels[i])
    print('\n')

Value labels for column 'C_Q07':
{1.0: 'Full-time employed (self-employed, employee)',
 2.0: 'Part-time employed (self-employed, employee)',
 3.0: 'Unemployed',
 4.0: 'Pupil, student',
 5.0: 'Apprentice, internship',
 6.0: 'In retirement or early retirement',
 7.0: 'Permanently disabled',
 8.0: 'In compulsory military or community service',
 9.0: 'Fulfilling domestic tasks or looking after children/family',
 10.0: 'Other',
 96.0: 'Valid skip',
 97.0: "Don't know",
 98.0: 'Refused',
 99.0: 'Not stated or inferred'}


Value labels for column 'YEARLYINCPR':
{1.0: 'Less than 10',
 2.0: '10 to less than 25',
 3.0: '25 to less than 50',
 4.0: '50 to less than 75',
 5.0: '75 to less than 90',
 6.0: '90 or more',
 9.0: 'Not stated or inferred'}


Value labels for column 'AGEG10LFS_T':
{1.0: '24 or less',
 2.0: '25-34',
 3.0: '35-44',
 4.0: '45-54',
 5.0: '55 plus',
 93.0: '<16',
 94.0: '>65',
 99.0: 'Not stated or inferred'}


Value labels for column 'RACETHN_4CAT':
{1.0: 'Hispanic',
 2.0: 'White',
 3.0: 'Black',
 6.0: 'Other race',
 9.0: 'Not stated or inferred'}


Value labels for column 'EDCAT6':
{1.0: 'Lower secondary or less (ISCED 1,2, 3C short or less)',
 2.0: 'Upper secondary (ISCED 3A-B, C long)',
 3.0: 'Post-secondary, non-tertiary (ISCED 4A-B-C)',
 4.0: 'Tertiary - professional degree (ISCED 5B)',
 5.0: 'Tertiary - bachelor degree (ISCED 5A)',
 6.0: 'Tertiary - master/research degree (ISCED 5A/6)',
 7.0: 'Tertiary - bachelor/master/research degree (ISCED 5A/6)',
 99.0: 'Not stated or inferred'}


Value labels for column 'GENDER_R':
{1.0: 'Male', 2.0: 'Female', 9.0: 'Not stated or inferred'}


Value labels for column 'J_Q04A':
{1.0: 'Yes',
 2.0: 'No',
 6.0: 'Valid skip',
 7.0: "Don't know",
 8.0: 'Refused',
 9.0: 'Not stated or inferred'}


Value labels for column 'REGION_US':
{1.0: 'Northeast', 2.0: 'Midwest', 3.0: 'South', 4.0: 'West'}

In [5]:
# value counts
for i in ['C_Q07','YEARLYINCPR','AGEG10LFS_T','RACETHN_4CAT','EDCAT6','GENDER_R','J_Q04A','REGION_US']:
    print(f"\033[1mValue counts for column '{i}':\033[0m")
    print(df0_labelled[i].value_counts(dropna=False), end='\n\n')

Value counts for column 'C_Q07':
Full-time employed (self-employed, employee)                  3241
Unemployed                                                    1343
Pupil, student                                                1059
Part-time employed (self-employed, employee)                  1009
In retirement or early retirement                              684
Fulfilling domestic tasks or looking after children/family     496
Permanently disabled                                           403
Other                                                          214
NaN                                                            191
Apprentice, internship                                          28
In compulsory military or community service                      2
Name: C_Q07, dtype: int64

Value counts for column 'YEARLYINCPR':
NaN                   4162
25 to less than 50    1185
50 to less than 75    1071
75 to less than 90     704
10 to less than 25     636
90 or more             491
Less than 10           421
Name: YEARLYINCPR, dtype: int64

Value counts for column 'AGEG10LFS_T':
25-34         2100
24 or less    2034
45-54         1301
35-44         1253
55 plus       1229
NaN            753
Name: AGEG10LFS_T, dtype: int64

Value counts for column 'RACETHN_4CAT':
White         5269
Black         1450
Hispanic      1101
Other race     641
NaN            209
Name: RACETHN_4CAT, dtype: int64

Value counts for column 'EDCAT6':
Upper secondary (ISCED 3A-B, C long)                     3637
Lower secondary or less (ISCED 1,2, 3C short or less)    1406
Tertiary - bachelor degree (ISCED 5A)                    1317
Tertiary - master/research degree (ISCED 5A/6)            801
Post-secondary, non-tertiary (ISCED 4A-B-C)               680
Tertiary - professional degree (ISCED 5B)                 630
NaN                                                       199
Name: EDCAT6, dtype: int64

Value counts for column 'GENDER_R':
Female    4659
Male      4011
Name: GENDER_R, dtype: int64

Value counts for column 'J_Q04A':
Yes    7398
No     1079
NaN     193
Name: J_Q04A, dtype: int64

Value counts for column 'REGION_US':
South        3555
Midwest      1882
Northeast    1753
West         1480
Name: REGION_US, dtype: int64

# Data Pre-processing

In [6]:
# data cleaning tracker 
report = pd.DataFrame({'task': 'start',
                       'nrow_changed': np.nan,
                       'ncol_changed': np.nan ,
                       'nrow_after': df0.shape[0],
                       'ncol_after': df0.shape[1]}, index = [0])
report

    task  nrow_changed  ncol_changed  nrow_after  ncol_after
0  start           NaN           NaN        8670        1340

### Filter age groups

In [7]:
df1 = df0[df0['AGEG10LFS_T'].isin([2,3,4])]
# df1 = df0.query("AGEG10LFS_T in (2,3,4)")

In [8]:
# update the tracker 
report = report.append(pd.DataFrame({'task': 'filter age groups',
                                     'nrow_changed': (df1.shape[0] - report.loc[max(report.index), 'nrow_after']), 
                                     'ncol_changed': (df1.shape[1] - report.loc[max(report.index), 'ncol_after']), 
                                     'nrow_after': df1.shape[0], 
                                     'ncol_after': df1.shape[1]}, index = [max(report.index)+1]))
report

                task  nrow_changed  ncol_changed  nrow_after  ncol_after
0              start           NaN           NaN        8670        1340
1  filter age groups       -4016.0           0.0        4654        1340

### Remove NaNs in select cols

In [9]:
df1 = df1.dropna(subset=['YEARLYINCPR','AGEG10LFS_T','RACETHN_4CAT','EDCAT6','GENDER_R','J_Q04A','REGION_US'])

In [10]:
# update the tracker 
report = report.append(pd.DataFrame({'task': 'remove NaNs',
                                     'nrow_changed': (df1.shape[0] - report.loc[max(report.index), 'nrow_after']), 
                                     'ncol_changed': (df1.shape[1] - report.loc[max(report.index), 'ncol_after']), 
                                     'nrow_after': df1.shape[0], 
                                     'ncol_after': df1.shape[1]}, index = [max(report.index)+1]))
report

                task  nrow_changed  ncol_changed  nrow_after  ncol_after
0              start           NaN           NaN        8670        1340
1  filter age groups       -4016.0           0.0        4654        1340
2        remove NaNs       -1762.0           0.0        2892        1340

### Create new variables or recode them into the same ones

In [11]:
# Low and High income
df1['LowIncome'] = np.where(df1['YEARLYINCPR'].isin([1,2]), 1, 0)
df1['HighIncome'] = np.where(df1['YEARLYINCPR'].isin([5,6]), 1, 0)
df1['YEARLYINCPR_R'] = np.where(df1['YEARLYINCPR'].isin([1,2]), 'Q1', 
                                np.where(df1['YEARLYINCPR']==3, 'Q2',
                                         np.where(df1['YEARLYINCPR']==4, 'Q3', 'Q4')))
df1['LowIncome'].value_counts(dropna=False)
df1['HighIncome'].value_counts(dropna=False)
df1['YEARLYINCPR_R'].value_counts(dropna=False)

0    2491
1     401
Name: LowIncome, dtype: int64

0    1987
1     905
Name: HighIncome, dtype: int64

Q4    905
Q3    798
Q2    788
Q1    401
Name: YEARLYINCPR_R, dtype: int64

In [12]:
# recode age
df1['AGEG10LFS_T'] = df1['AGEG10LFS_T'].replace({2: '2534', 3: '3544', 4: '4554'})
df1['AGEG10LFS_T'].value_counts(dropna=False)

2534    1356
4554     786
3544     750
Name: AGEG10LFS_T, dtype: int64

In [13]:
# recode race
df1['RACETHN_4CAT'] = df1['RACETHN_4CAT'].replace({1: 'Hispanic', 2: 'White', 3: 'Black', 6: 'Other'})
df1['RACETHN_4CAT'].value_counts(dropna=False)

White       1893
Black        400
Hispanic     377
Other        222
Name: RACETHN_4CAT, dtype: int64

In [14]:
# recode edcat into 3 groups
df1['EDCAT3'] = np.where(df1['EDCAT6'].isin([1,2]), 'Secondary',
                         np.where(df1['EDCAT6']==3, 'Non-tertiary', 'Tertiary'))
df1['EDCAT3'].value_counts(dropna=False)

Tertiary        1355
Secondary       1255
Non-tertiary     282
Name: EDCAT3, dtype: int64

In [15]:
# recode Gender and create FEMALE
df1['FEMALE'] = np.where(df1['GENDER_R']==2, 1, 0)
df1['GENDER_R'] = np.where(df1['GENDER_R']==1, 'Male', 'Female')
df1['FEMALE'].value_counts(dropna=False)
df1['GENDER_R'].value_counts(dropna=False)

1    1479
0    1413
Name: FEMALE, dtype: int64

Female    1479
Male      1413
Name: GENDER_R, dtype: int64

In [16]:
# recode born in the country
df1['US_born'] = np.where(df1['J_Q04A']==1, 1, 0)
df1['US_born'].value_counts(dropna=False)

1    2447
0     445
Name: US_born, dtype: int64

In [17]:
# recode US regions
df1['REGION_US'] = np.where(df1['REGION_US']==1, 'Northeast',
                            np.where(df1['REGION_US']==2, 'Midwest',
                                     np.where(df1['REGION_US']==3, 'South', 'West')))
df1['REGION_US'].value_counts(dropna=False)

South        1187
Midwest       645
Northeast     559
West          501
Name: REGION_US, dtype: int64

In [18]:
# calculate scaled sum of pvlit and pvnum as cog_skills
## df1['STLITNUM1'] = np.asarray(df1[['PVLIT1', 'PVNUM1']].sum(axis=1))
## df1['STLITNUM1'] = (df1['STLITNUM1'] - df1['STLITNUM1'].mean()) / df1['STLITNUM1'].std()
from sklearn.preprocessing import scale
lit_cols = df1.filter(regex='^PVLIT').columns
num_cols = df1.filter(regex='^PVNUM').columns
for i in range(len(lit_cols)):
    col_name = 'STLITNUM{}'.format(i + 1)
    df1[col_name] = scale(df1[[lit_cols[i], num_cols[i]]].sum(axis=1).values.reshape(-1, 1))
# Note that scale requires the input to be a 2-dimensional array, so 
# we use the values.reshape(-1, 1) code to ensure that the input is a 2-dimensional array

In [19]:
# update the tracker 
report = report.append(pd.DataFrame({'task': 'create new cols',
                                     'nrow_changed': (df1.shape[0] - report.loc[max(report.index), 'nrow_after']), 
                                     'ncol_changed': (df1.shape[1] - report.loc[max(report.index), 'ncol_after']), 
                                     'nrow_after': df1.shape[0], 
                                     'ncol_after': df1.shape[1]}, index = [max(report.index)+1]))
report

                task  nrow_changed  ncol_changed  nrow_after  ncol_after
0              start           NaN           NaN        8670        1340
1  filter age groups       -4016.0           0.0        4654        1340
2        remove NaNs       -1762.0           0.0        2892        1340
3    create new cols           0.0          16.0        2892        1356

### Remove outliers

In [20]:
grouped = df1.groupby(['GENDER_R', 'RACETHN_4CAT', 'EDCAT3'])
df1['q1'] = grouped['EARNMTHBONUSUS_C'].transform('quantile', 0.25)
df1['q3'] = grouped['EARNMTHBONUSUS_C'].transform('quantile', 0.75)
df1['iqr'] = df1['q3'] - df1['q1']
df1['lower'] = df1['q1'] - 4 * df1['iqr']
df1['upper'] = df1['q3'] + 4 * df1['iqr']
df1['EARNMTHBONUSUS_C_outlier'] = np.where(df1['EARNMTHBONUSUS_C'] > df1['upper'], 'high',
                                           np.where(df1['EARNMTHBONUSUS_C'] < df1['lower'], 'low',
                                                    np.where(df1['EARNMTHBONUSUS_C'].isna(), 'missing', 'normal')))
df1 = df1[df1['EARNMTHBONUSUS_C_outlier'] != 'high']
df1 = df1.drop(columns=['q1', 'q3', 'iqr', 'lower', 'upper', 'EARNMTHBONUSUS_C_outlier'])

In [21]:
# update the tracker 
report = report.append(pd.DataFrame({'task': 'remove outliers',
                                     'nrow_changed': (df1.shape[0] - report.loc[max(report.index), 'nrow_after']), 
                                     'ncol_changed': (df1.shape[1] - report.loc[max(report.index), 'ncol_after']), 
                                     'nrow_after': df1.shape[0], 
                                     'ncol_after': df1.shape[1]}, index = [max(report.index)+1]))
report

                task  nrow_changed  ncol_changed  nrow_after  ncol_after
0              start           NaN           NaN        8670        1340
1  filter age groups       -4016.0           0.0        4654        1340
2        remove NaNs       -1762.0           0.0        2892        1340
3    create new cols           0.0          16.0        2892        1356
4    remove outliers         -23.0           0.0        2869        1356

### Merge groups

In [22]:
# Merge groups: Other-Non-tertiary cell is relatively small; recode them as Other-Tertiary
# save number of rows affected
nrow_changed = df1[(df1['RACETHN_4CAT']=="Other") & (df1['EDCAT3']=="Non-tertiary")].shape[0]
# merge
df1['EDCAT3'] = np.where((df1['RACETHN_4CAT']=="Other") & (df1['EDCAT3']=="Non-tertiary"), "Tertiary", df1['EDCAT3'].astype(str))

In [23]:
# update the tracker 
report = report.append(pd.DataFrame({'task': 'merge groups',
                                     'nrow_changed': "(" + str(nrow_changed) + ")", 
                                     'ncol_changed': (df1.shape[1] - report.loc[max(report.index), 'ncol_after']), 
                                     'nrow_after': df1.shape[0], 
                                     'ncol_after': df1.shape[1]}, index = [max(report.index)+1]))
report

                task nrow_changed  ncol_changed  nrow_after  ncol_after
0              start          NaN           NaN        8670        1340
1  filter age groups      -4016.0           0.0        4654        1340
2        remove NaNs      -1762.0           0.0        2892        1340
3    create new cols          0.0          16.0        2892        1356
4    remove outliers        -23.0           0.0        2869        1356
5       merge groups         (14)           0.0        2869        1356

### Replace NaNs

In [24]:
# replace NA EARNMTHBONUSUS_C with the mean incomes for YEARLYINCPR
# save number of rows affected
nrow_changed = df1['EARNMTHBONUSUS_C'].isna().sum()
# replace NA 
grouped = df1.groupby('YEARLYINCPR')
df1['EARNMTHBONUSUS_C_mean'] = grouped['EARNMTHBONUSUS_C'].transform('mean')
df1['EARNMTHBONUSUS_C'] = np.where(df1['EARNMTHBONUSUS_C'].isna(), df1['EARNMTHBONUSUS_C_mean'], df1['EARNMTHBONUSUS_C'])
df1 = df1.drop(columns = ['EARNMTHBONUSUS_C_mean'])

In [25]:
# update the tracker 
report = report.append(pd.DataFrame({'task': 'replace NaNs',
                                     'nrow_changed': "(" + str(nrow_changed) + ")", 
                                     'ncol_changed': (df1.shape[1] - report.loc[max(report.index), 'ncol_after']), 
                                     'nrow_after': df1.shape[0], 
                                     'ncol_after': df1.shape[1]}, index = [max(report.index)+1]))
report

                task nrow_changed  ncol_changed  nrow_after  ncol_after
0              start          NaN           NaN        8670        1340
1  filter age groups      -4016.0           0.0        4654        1340
2        remove NaNs      -1762.0           0.0        2892        1340
3    create new cols          0.0          16.0        2892        1356
4    remove outliers        -23.0           0.0        2869        1356
5       merge groups         (14)           0.0        2869        1356
6       replace NaNs        (349)           0.0        2869        1356

### Select columns

In [26]:
cols = (['LowIncome','HighIncome','FEMALE',
        'C_Q07','YEARLYINCPR','GENDER_R','AGEG10LFS_T','RACETHN_4CAT','EDCAT6','EDCAT3',
        'C_Q09_C','ISCOSKIL4','EARNMTHBONUSUS_C','EARNMTHBONUSPPPUS_C','D_Q18A_T',
        'J_Q04A','US_born','REGION_US'] + 
        list(df1.loc[:, 'LITSTATUS':'PVNUM10'].columns) + 
        list(df1.loc[:, 'STLITNUM1':'STLITNUM10'].columns) +
        ['VEMETHOD','VENREPS'] + list(df1.loc[:, 'SPFWT0':'SPFWT80'].columns))
df1 = df1.loc[:, cols]

In [27]:
# update the tracker 
report = report.append(pd.DataFrame({'task': 'select cols',
                                     'nrow_changed': (df1.shape[0] - report.loc[max(report.index), 'nrow_after']), 
                                     'ncol_changed': (df1.shape[1] - report.loc[max(report.index), 'ncol_after']), 
                                     'nrow_after': df1.shape[0], 
                                     'ncol_after': df1.shape[1]}, index = [max(report.index)+1]))
report

                task nrow_changed  ncol_changed  nrow_after  ncol_after
0              start          NaN           NaN        8670        1340
1  filter age groups      -4016.0           0.0        4654        1340
2        remove NaNs      -1762.0           0.0        2892        1340
3    create new cols          0.0          16.0        2892        1356
4    remove outliers        -23.0           0.0        2869        1356
5       merge groups         (14)           0.0        2869        1356
6       replace NaNs        (349)           0.0        2869        1356
7        select cols            0       -1223.0        2869         133

# Export cleaned data

In [28]:
df1.to_csv(os.path.join(fpath, "Cleaned", "Data_v1_py.csv"), index=False)